version: "3"

services:
  redis:
      container_name: "${PROJECT_NAME}_redis"
      ports: 
        - "6379:6379"
      image: redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: henry
      POSTGRES_PASSWORD: gsx
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "info@mdo-ito.de"
      PGADMIN_DEFAULT_PASSWORD: "gsx"
    ports:
      - "8080:80"